{
 "title": "mintor_dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Number of Messages",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "baking_assistant",
     "rawSql": "SELECT COUNT(question) FROM conversations LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of Relevant Ans",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 13, "x": 8, "y": 0 },
   "targets": [
    {
     "dataset": "baking_assistant",
     "rawSql": "SELECT relevance, COUNT(id) FROM conversations GROUP BY relevance LIMIT 50 "
    }
   ]
  },
  {
   "title": "Token Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "baking_assistant",
     "rawSql": "SELECT SUM(ans_total_tokens) AS answer_tokens_used, \"timestamp\", SUM(eval_total_tokens) AS evaluation_tokens_used FROM conversations GROUP BY \"timestamp\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total Cost",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 10, "y": 8 },
   "targets": [
    {
     "dataset": "baking_assistant",
     "rawSql": "SELECT \"timestamp\", SUM(total_cost) FROM conversations GROUP BY \"timestamp\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Response that are not relevant",
   "type": "table",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "baking_assistant",
     "rawSql": "SELECT relevance, question, relevance_explanation FROM conversations WHERE relevance <> 'RELEVANT' LIMIT 50 "
    }
   ]
  }
 ]
}